### ISSUE TITLE
Unable to download on Debian

### ISSUE THREAD

**Issue by ghost** [andrewrothstein/ansible-kubectl#1]
Git commit https://github.com/andrewrothstein/ansible-kubectl/commit/08983eb523d9d96a603ef936f59275527b129fb9 to "added support for Darwin by easing the hardcoding around OS" breaks installs on Ubuntu.

The URL constructed for Debian is:
- https://storage.googleapis.com/kubernetes-release/release/v1.3.5/bin/debian/amd64/kubectl

It should be:
- https://storage.googleapis.com/kubernetes-release/release/v1.3.5/bin/linux/amd64/kubectl

**Comment by andrewrothstein** [comment]
Thanks for the contribution. I accepted the pull request and published v1.0.2 of the role to that galaxy.
