### ISSUE TITLE
Missing checksums for v1.20.6 and v1.20.7

### ISSUE THREAD

**Issue by infra-monkey** [andrewrothstein/ansible-kubectl#11]
Hi,

Trying to update my kubectl today to version v1.20.7 but the role fails (defaults/main.yml) doesn't contain the checksums for v1.20.6 and v1.20.7.

The reported error is :

> "The task includes an option with an undefined variable. The error was: {{ kubectl_checksums[kubectl_ver][kubectl_os][kubectl_platform] }}: 'dict object' has no attribute 'v1.20.7'\n\nThe error appears to be in '/runner/requirements_roles/andrewrothstein.kubectl/tasks/main.yml': line 21, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: downloading {{ kubectl_url }} to {{ kubectl_install_exe }}...\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"

Nothing urgent as v1.20.5 is stil compatible...
Regards

**Comment by andrewrothstein** [comment]
added in v1.1.60

**Comment by infra-monkey** [comment]
Perfect ! thanks
